# Generated by Django 5.2.3 on 2025-07-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='author',
            field=models.CharField(default='none'),
        ),
    ]
