# Generated by Django 5.2.3 on 2025-07-14 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='dateCreated',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='dateUpdated',
            new_name='updated_date',
        ),
    ]
