# Generated by Django 5.2.3 on 2025-07-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_datecreated_notes_created_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
