# Generated by Django 5.2.3 on 2025-07-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_102', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Human',
            new_name='Person',
        ),
    ]
