# Generated by Django 5.2.3 on 2025-07-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
