# Generated by Django 5.2.3 on 2025-07-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contents_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contents',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
