# Generated by Django 5.2.3 on 2025-07-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_contents_image_alter_contents_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/images'),
        ),
    ]
