# Generated by Django 5.2.3 on 2025-07-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contents',
            name='author',
        ),
    ]
