# Generated by Django 5.2.3 on 2025-07-08 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_contents_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.author'),
        ),
    ]
