# Generated by Django 5.2.3 on 2025-06-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField()),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
