# Generated by Django 5.2.3 on 2025-07-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brandName',
            new_name='name',
        ),
    ]
