# Generated by Django 5.2.3 on 2025-07-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(choices=[('chitwan', 'Chitwan'), ('kathmandu', 'Kathmandu'), ('pokhara', 'Pokhara')], max_length=30),
        ),
    ]
